---
title: "01 Intro to the tidyverse"
author: "Joschka Schwarz"
date: "2021-04"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Challenge #1

Last compiled: `r Sys.Date()`


## Analysis based on States

```{r}
library(lubridate)
library(tidyverse)
library(readxl)

bikes_tbl <- read_excel("ds_data/01_bike_sales/01_raw_data/bikes.xlsx")
orderlines_tbl <- read_excel ("ds_data/01_bike_sales/01_raw_data/orderlines.xlsx")
bikeshops_tbl <- read_excel("ds_data/01_bike_sales/01_raw_data/bikeshops.xlsx")
bike_orderlines_joined_tbl <- orderlines_tbl %>% left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>% left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

bike_oderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>% 
  separate(col=location, into = c("City", "State"), sep = ",")  # Separate State and City into 2 different columns


sales_by_state_tbl_1 <- bike_oderlines_wrangled_tbl %>% 
  mutate(total_price = price * quantity) %>%                    # get the total price
  select(State, total_price) %>%                                # choose State and total price as analysis variables
  group_by(State) %>%                                           # group by states
  summarise(sales=sum(total_price)) %>%                         # summarize sales
  mutate(sales_text = scales::dollar(sales,big.mark = ".",      # Adding currency format
                                          decimal.mark = ",", 
                                          prefix = "", 
                                          suffix = "€"))

sales_by_state_tbl_1 %>% 
  ggplot(aes(x=State,y=sales)) +                                # Canvas with State(x-axis) and sales (y-axis)            
  geom_col(fill = "#2DC6D6") + 
  geom_smooth(method = "lm", se = FALSE) +                      # Add trendline
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".",decimal.mark = ",", prefix = "", suffix = "€")) +  # Currency format
  labs(title = "Revenue by State", subtitle = "", x= "State", y = "Revenue")                                          # Naming titles and labels on x-y axes
```




# Challenge #2

Last compiled: `r Sys.Date()`


## Analysis based on States and Year
```{r plot, fig.width=13, fig.height=10}
sales_by_state_year_tbl <- bike_oderlines_wrangled_tbl %>%
  mutate (total_price = price*quantity) %>%            # get the total price
  select(order.date, total_price, State) %>%           # Choosing total price, state, and year as analysis variables
  mutate(year=year(order.date)) %>%                    # Adding the year column
  group_by(year,State) %>%                             # Grouping by State and Year
  summarise(sales=sum(total_price)) %>%                # Summarizing sales
  ungroup() %>%
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "",
                                     suffix = "€"))    # Currency format


sales_by_state_year_tbl %>% 
  ggplot(aes(x=year, y=sales, fill = State)) +
  geom_col() +
  facet_wrap(~State) +
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".",
                                                    decimal.mark = ",",
                                                    prefix = "",
                                                    suffix = "€")) +
  labs(
    title = "Revenue by State and Year",
    fill = "State"
  )
```