---
title: "02 Data Acqusition"
date: "2021-04"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
# Challenge #1

## Most recent tweets about Covid-19 (#Covid-19) retrieved from twitter

```{r}
library(httr)
library(rtweet)
library(dplyr)
library (reactable)
library(rtweet)
library(rstudioapi)
library(glue) # Retrieving the relevant libraries
  
twitter_token <- create_token(app = "Saif187e", 
                              consumer_key = keyring::key_get("my-database-2", "myusername"), 
                              consumer_secret = keyring::key_get("my-database", "myusername"),
                              access_token = keyring::key_get("my-database-3", "myusername"),
                              access_secret = keyring::key_get("my-database-1", "myusername"),
                              set_renv = TRUE) #Accessing twitter's API using the token

tweet_df <- search_tweets("#Covid-19", n=10, include_rts = FALSE, token = NULL) # Searching for the latest 10 tweets about Covid-19
tweets <- tweet_df %>% select(user_id, status_id, text, favorite_count, retweet_count, screen_name, created_at) # Selecting the desired analysis parameters 
tweet_data_table <- select(tweets, -user_id, -status_id)

reactable(tweet_data_table,
          filterable = TRUE, searchable = TRUE, bordered = TRUE, striped = TRUE, highlight = TRUE, defaultPageSize = 25, showPageSizeOptions = TRUE, showSortable = TRUE, pageSizeOptions = c(25,50,75,100,200), defaultSortOrder = "desc",
          columns = list(
            text = colDef (html = TRUE, minWidth = 190, resizable = TRUE),
            favorite_count = colDef (filterable = FALSE),
            retweet_count = colDef (filterable = FALSE),
            screen_name = colDef(defaultSortOrder = "asc"),
            created_at = colDef(defaultSortOrder = "asc")
          ) # table creation using the reactable () function
)
```

# Challenge #2

## Data from endurance bikes scraped from the "rosebikes" website

```{r}
library(tidyverse) 
library(rvest)     
library(xopen)     
library(jsonlite)  
library(glue)      
library(stringi) # Retrieving the relevant libraries
 
url_2 <- "https://www.rosebikes.com/bikes/road/endurance" #Assigning the url manually (since it's only one category)

html_bike_category_2 <- read_html(url_2)

bike_name_tbl_2 <- html_bike_category_2 %>%
  html_nodes(css = '.catalog-category-bikes__title-text') %>%
  html_text2() %>%
  enframe(name = "position", value = "model name") # Retrieving the model names from the url

bike_price_tbl_2 <- html_bike_category_2 %>%
  html_nodes(css = '.catalog-category-bikes__price-title') %>%
  html_text2() %>%
  stringr::str_remove(pattern = "[a-z]") %>% 
  stringr::str_remove(pattern = "[a-z]") %>% 
  stringr::str_remove(pattern = "[a-z]") %>% 
  stringr::str_remove(pattern = "[a-z]") %>% 
  stringr::str_remove(pattern = "[^a-zA-Z0-9_]") %>% 
  stringr::str_remove(pattern = "[^a-zA-Z0-9_]") %>% 
  enframe(name = "position", value = "price in Euros")  # Retrieving the prices from the url

bike_desc_tbl_2 <- html_bike_category_2 %>%
  html_nodes(css = '.catalog-category-bikes__subtitle') %>%
  html_text2() %>%
  enframe(name = "position", value = "description") # Retrieving the descriptions from the url

bike_url_tbl_2  <- html_bike_category_2 %>%
    html_nodes(css = ".row .align-middle > a") %>%
    html_attr("href") %>%
    str_remove(pattern = "\\?.*") %>%
    enframe(name = "position", value = "subdirectory") # Retrieving the relevant url subdirectories for each bike model

bike_data_tbl_2 <- (bike_name_tbl_2) %>% 
  left_join(bike_price_tbl_2) %>%
  left_join(bike_desc_tbl_2) %>% 
  left_join(bike_url_tbl_2) # organizing data in a table

bike_data_tbl_2
```