---
title: "04 Data Visualization"
date: "2021-04"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
# Data Visualization 
## First Question
### Confirmed Covid-19 cases as of 08-05-2021 (in some countries)

```{r}
library(tidyverse)
library(scales)
library(ggplot2)
library(dplyr)
library(data.table)
library(rvest) 
library(magrittr)
library(readr)
library(lubridate)
library (ggmap)

covid_data_tbl_1 <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")

main_tbl <- covid_data_tbl_1 %>% select(date, location, total_cases) 
sub_tbl <- main_tbl %>% filter(location == "Germany" | location == "France" | location == "Spain" | location == "United Kingdom" | location == "United States")

plt <- ggplot(sub_tbl, aes(x=date, y = total_cases, group = location, colour = location)) + 
  geom_line() +
  theme_minimal() + 
  labs( fill = "Continent / Country",
    title = "Covid-19 confirmed cases worldwide",
    subtitle = "As of 04/05/2021",
    x = "Challenge 1",
    y = "Cumulative Cases") +
  scale_y_continuous(labels = scales::dollar_format(scale = 1/1e6, prefix = "", suffix = "M")) +
  scale_x_date(breaks = date_breaks("months"), labels = date_format("%B'%y")) +
  theme(axis.text.x = element_text(angle = 45)) + 
  scale_colour_manual(values = c("darkorange1", "blueviolet", "deeppink", "lawngreen", "darkgoldenrod1")) +
  geom_label(label =  "32,686,256",
             vjust = 1, 
             hjust = 1,
             size  = 4,
             fill  = "darkgoldenrod1",
             color = "white",
             fontface = "italic",
             data = sub_tbl %>%
               filter(location == "United States" & date >= as.Date("2021-05-08"))) 
plt + theme(
  legend.position = "bottom",
  legend.box = "vertical"
) 
```

## Second Question
### Mortality Rate of Covid-19 worldwide
```{r}
library(tidyverse)
library(scales)
library(ggplot2)
library(dplyr)

covid_data_tbl_1 <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")

tbl_1 <- covid_data_tbl_1 %>% select(date, location, total_deaths, population)
tbl_2 <- tbl_1 %>% filter(date == as.Date("2021-05-04"))
covid_2 <-  tbl_2 %>%
  mutate(mortality = (total_deaths/population)) %>% 
  rename(region = location) %>% 
  mutate(region = case_when(
    
    region == "United Kingdom" ~ "UK",
    region == "United States" ~ "USA",
    region == "Democratic Republic of Congo" ~ "Democratic Republic of the Congo",
    TRUE ~ region
    
  )) %>%
  distinct()

world_map <- map_data("world")

combined <- world_map[covid_2$region %in% covid_2$region, ]
combined$mort <- covid_2$mortality[match(combined$region, covid_2$region)]
countries <- unique(combined$region)
CDF <- data.frame(label1=countries)

for(i in CDF){
  combined$mort <- ifelse(combined$region %in% CDF$label1[i], (covid_2$mortality), combined$mort)
}


 ggplot(combined, aes(x=long, y=lat, group=group, fill=mort)) +
  geom_polygon(colour = "white") +
   scale_fill_gradient(low = "red", high = "red4", limits = c(-0.0005, 0.0025), labels = percent) +
  theme_minimal() +
  labs(fill="Mortality Rate (%)", title = "Confirmed COVID-19 deaths relative to the size of the population",
       subtitle = "Around 3 Million confirmed COVID-19 deaths worldwide", x="Challenge 2", y="") +
  scale_y_continuous(breaks = c()) +
  scale_x_continuous(breaks = c()) +
  theme(panel.border = element_blank())
```